### ISSUE TITLE
It does not work with little memory | Android

### ISSUE THREAD

**Issue by AngelCareaga** [ionic-team/ionic-storage#151] opened 2018-05-20 02:55 UTC
It does not store anything with little space in memory, how is that valid?
Or alternative?

**Comment by carpediemy** [comment] 2018-05-29 07:52
@AngelCareaga I ran into the same problem, only after clearing 1gb or so, it started working. Did you find the cause for this?

**Comment by AngelCareaga** [comment] 2018-05-29 17:07
@carpediemy 

No, just validate that if the response to storage does not return data to me, then there is an error with "little memory", and that's it, but I'm still investigating another way, that's temporary.

Something like that looks:
```
// Verify if I have data saved
this._preferencesProvider.hasCheckPreferences()
      .then(res => {
        // Return data saved
        if (res) {
            // Something
        } else {
          this.showLongToast('messageErrorStorage'); // Show error message
        }
      })
      .catch(error => {
        console.log(`Error:   ${error}`);
        return Promise.reject(error);
      });
```

**Comment by mhartington** [comment] 2018-09-05 17:37
Hi there! I'm going to close this as this is not an issue with the library, but a quirk of the browser/platform.

**Closed by mhartington** 2018-09-05 17:37 UTC
