### ISSUE TITLE
promises don't resolve and driver is null

### ISSUE THREAD

**Issue by webmass** [ionic-team/ionic-storage#161] opened 2019-01-03 12:39 UTC
Hi there, 

Happy new year ;)

So I'm trying to use IonicStorage in a ionic 4 app, I'm testing it in the browser, but the promises of ready, get and set methods never resolve, and when I log the driver with storage.driver, the result is null!

My config in my app.module.ts : 

````
import { IonicStorageModule } from '@ionic/storage';

@NgModule({
...
imports: [
...
IonicStorageModule.forRoot({
      name: '__mydb',
      driverOrder: ['sqlite', 'indexeddb', 'websql', 'localstorage']
    }),
]
...
````

I tried every kind of driverOrder, same result.
So I may switch back to nativeStorage.

Any ideas?
I'm already familiar with localForage.

Cheers

**Comment by tekagesolutions** [comment] 2019-02-27 15:14
I have a similar issue on an Ionic 3 app.  I call the ready promise and have a then and catch in there and it just skips everything and never resolves.  Any help appreciated. 

`public async get(settingName) {
this.storage.ready().then(() => {
return this.storage.get(``setting:${ settingName }``)
})
.catch( err => {
console.log("Storage Get Error");
return Promise.reject(err);
}
);
}
`

**Comment by saikirangit** [comment] 2020-07-29 21:46
Were you guys able to resolve this?

**Comment by danikoala** [comment] 2020-07-31 13:54
I have the same problem after updating to Angular 10. The curious thing is that when I'm under a browser platform everything is ok, but when I execute the same application inside an Electron (v9) wrapper, the driver is always null.

**Comment by saikirangit** [comment] 2020-08-01 21:59
what package version are you on??

**Comment by danikoala** [comment] 2020-08-03 07:15
@ionic/storage 2.3.0
electron 9.1.2

**Comment by danikoala** [comment] 2020-08-03 10:34
Problem was solved rolling back to version 2.2.0.

**Comment by saikirangit** [comment] 2020-08-03 14:41
https://github.com/ionic-team/ionic-storage/commit/2ea8583d774a96c3c150e944c8fe925d0cf69f3d#commitcomment-41119643

This commit was causing the issue for me and the driver was always null... I had to downgrade the version too and it worked.

**Comment by looorent** [comment] 2020-08-05 13:52
I had the same issue. After upgrading to Angular 10 and ionic-storage `2.3.0`, the storage's driver is always `null`.

When debugging ionic-storage, I found that now (version `2.3.0`?), the `Storage` constructor checks for the presence of a `process` attribute on `window` (this is maybe the case in previous versions, but in my case, this occurred with version `2.3.0`).
https://github.com/ionic-team/ionic-storage/blob/6a70ed75c75962091e21c57d618053ce5be0ece0/src/storage.ts#L113-L117

If you have an object `process` defined on `window` (e.g. in your polyfills), ionic-storage will always pick a "noop" driver, which is a blank implementation. For some reason, this polyfill was added when migrating from Ionic 3 to 4, long time ago. In my case, `window.process` was useless. 

Removing this attribute solved my problem.

**Comment by Fowlet** [comment] 2020-08-15 11:35
Just spent several days stuck on this. As part of a larger refactor, ionic-storage got updated.

The upshot is that in ionic browser scenarios, by default, storage silently fails to write. There is no thread to follow to a solution, I stumbled upon this thread by blind luck. How did this get merged?

**Comment by saikirangit** [comment] 2020-08-15 23:09
I got my storage version downgraded to 2.1.3 to get it working

**Comment by peterlai107** [comment] 2020-08-18 10:00
same problem, the driver was always null.

**Comment by jbgtmartin** [comment] 2020-08-20 10:00
In my case, this is due to the fact that I use `pouchdb` in my project, which requires to add a polyfill for `process`:

```ts
// polyfills.ts
(window as any).process = {};
```
See https://github.com/pouchdb/pouchdb/issues/7263

So reverting to 2.2.0 fixes this issue, but then I can't compile anymore with Angular 10 due to this [fix](https://github.com/ionic-team/ionic-storage/commit/1e40fffb93895c791761221e808ac056dd714d51) that has been added in 2.3.0 🙂

**Comment by billygerhard** [comment] 2020-08-30 16:38
I also had to downgrade to 2.2.0. This issue has been open for a year and a half. Can someone please fix the latest release?

**Comment by mhartington** [comment] 2020-08-31 13:05
Hey folks, looking into this. Could someone summarize what's going on?

**Comment by jbgtmartin** [comment] 2020-08-31 13:20
Hi,

The issue is that since commit 2ea8583, the constructor falls back to the noop driver if `window.process` is defined.

In my case, I'm using another library (PouchDB), which requires to polyfill `window.process` (see [here](https://github.com/pouchdb/pouchdb/issues/7263))

So I have to add the following lines to my polyfills.ts:
```ts
(window as any).process = {};
(window as any).process.nextTick = setTimeout;
```

But then Ionic Storage will think that I'm in a node environment, and provide the loop driver instead of IndexedDB or SQLite etc.


So maybe PouchDB should not polyfill `window.process` like this, but the result is that it creates a conflict and that Ionic Storage thinks it's running in Node instead of browser...

**Comment by mhartington** [comment] 2020-08-31 13:37
Hmm, alright. Yeah, I'm of the opinion that pouchDB should not be polyfiling `window.process`, seems like a bad idea that could cause a lot of problems (like this).


I'll see if I can't get someone working on pouch to take a look.

**Comment by billygerhard** [comment] 2020-08-31 14:12
I am just using localstorage. I am not doing anything special. I only install @ionic/storage. So the package I was working on had issues with storage, and I downgraded and it worked fine. I spun up a blank starter app, and the newest version started working fine. Could it be a conflict or something with a dependency, maybe not the standard package? I am not using the external DB dependancies like the others. When I logged the driver on my actual project, I got `null`. When I log it on the base starter, I get `asyncStorage`

These are the dependancies from the package that didn't work.
```JSON
"dependencies": {
    "@angular/common": "^9.1.12",
    "@angular/core": "^9.1.12",
    "@angular/fire": "^6.0.2",
    "@angular/forms": "^9.1.12",
    "@angular/platform-browser": "^9.1.12",
    "@angular/platform-browser-dynamic": "^9.1.12",
    "@angular/router": "^9.1.12",
    "@capacitor/core": "^2.4.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/splash-screen": "^5.28.0",
    "@ionic-native/status-bar": "^5.28.0",
    "@ionic/angular": "^5.3.2",
    "@ionic/storage": "^2.2.0",
    "core-js": "^2.5.4",
    "firebase": "^7.19.0",
    "ngx-childprocess": "0.0.6",
    "ngx-electron": "^2.2.0",
    "rxjs": "^6.5.5",
    "tslib": "^1.13.0",
    "twitch": "^4.2.0-pre.6",
    "twitch-auth": "^4.2.0-pre.6",
    "twitch-chat-client": "^4.1.4",
    "twitch-pubsub-client": "^4.1.4",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.12",
    "@angular/cli": "^9.1.12",
    "@angular/compiler": "^9.1.12",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.1.12",
    "@babel/compat-data": "~7.8.0",
    "@capacitor/cli": "^2.4.0",
    "@ionic/angular-toolkit": "^2.3.3",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.12.54",
    "codelyzer": "^5.1.2",
    "electron": "^10.1.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "^5.4.4",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "^3.8.3"
  },
```
These are the dependencies from the project that isn't working.
```JSON
"dependencies": {
    "@angular/common": "~10.0.0",
    "@angular/core": "~10.0.0",
    "@angular/forms": "~10.0.0",
    "@angular/platform-browser": "~10.0.0",
    "@angular/platform-browser-dynamic": "~10.0.0",
    "@angular/router": "~10.0.0",
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^5.0.0",
    "@ionic/storage": "^2.3.0",
    "rxjs": "~6.5.5",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1000.0",
    "@angular/cli": "~10.0.5",
    "@angular/compiler": "~10.0.0",
    "@angular/compiler-cli": "~10.0.0",
    "@angular/language-service": "~10.0.0",
    "@ionic/angular-toolkit": "^2.3.0",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~3.3.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  },
```

**Comment by mhartington** [comment] 2020-08-31 14:14
@billygerhard Do you have a sample project we can look at? A Package.json is nice, but i need a sample project to look at.

**Comment by billygerhard** [comment] 2020-08-31 14:29
I can't replicate it with a blank project. I can see if I can keep trying. I don't know what I did to break it.

**Comment by mhartington** [comment] 2020-08-31 17:12
I've published a nightly tag that _should_ help here.


```
npm i @ionic/storage@nightly
```

**Comment by billygerhard** [comment] 2020-08-31 19:32
That gave me an error `ERROR in Cannot read property '0' of undefined`

**Comment by mhartington** [comment] 2020-08-31 20:26
Can you please provide a sample project to look at? I cannot replicate this on my end. If not, please update your other deps.

**Comment by saikirangit** [comment] 2020-09-01 02:28
For some reason it does not happen if it is base project with just storage... happens when I include in my main project

**Comment by jbgtmartin** [comment] 2020-09-01 08:44
I wasn't able to install 2.3.1-beta.0 from npm directly, it gave me typescript import error (I also tried to delete node_modules and package-lock.json). I couldn't really understand why, because the type declarations are present and they are the same as in 2.3.0...
```
error TS2307: Cannot find module '@ionic/storage' or its corresponding type declarations.
import { IonicStorageModule } from '@ionic/storage';
```

So I just replaced the bundles, esm2015 etc folders from 2.3.0 with the ones from 2.3.1-beta.0, and I can confirm that Ionic Storage is working fine with PouchDB, it doesn't select the noop driver anymore.

**Comment by mhartington** [comment] 2020-09-01 19:12
If this looks good...I'll merge my changes in and cut a stable release. But if there are any other issues, please let me know and provide a sample project.

**Comment by billygerhard** [comment] 2020-09-01 19:34
I added the nightly to my base project and it doesn't build 

https://github.com/billygerhard/ionic-storage-example

```
ionic build
> ng.cmd run app:build

ERROR in src/app/app.module.ts:11:34 - error TS2307: Cannot find module '@ionic/storage' or its corresponding type declarations.

11 import {IonicStorageModule} from "@ionic/storage";
                                    ~~~~~~~~~~~~~~~~
src/app/storage-test/storage-test.page.ts:2:23 - error TS2307: Cannot find module '@ionic/storage' or its corresponding type declarations.

2 import {Storage} from "@ionic/storage";
                        ~~~~~~~~~~~~~~~~

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.
```

**Comment by mhartington** [comment] 2020-09-01 19:51
Ahhh, that is my fault, bad npm publish 😬 

Just pushed a new nightly which should be good.

```
npm install @ionic/storage@nightly
```

**Comment by billygerhard** [comment] 2020-09-01 20:02
Others are saying that the latest release broke browser storage like I'm experiencing too 

https://github.com/ionic-team/ionic-storage/commit/2ea8583d774a96c3c150e944c8fe925d0cf69f3d#r41887124

**Comment by billygerhard** [comment] 2020-09-01 20:34
That latest push, beta.1 seems to have fixed my issue.

**Comment by mhartington** [comment] 2020-09-01 20:42
Can I get a confirmation from anyone else here? @saikirangit, @danikoala, @looorent, @Fowlet, @jbgtmartin

**Comment by looorent** [comment] 2020-09-01 21:11
I have moved from `2.3.0` to `2.3.1-beta.1` (I got rid of every `window.process` reference so I did not suffer from this noop driver issue).
It is a real-life project so I cannot share our code. However, everything looks ok:
* Build works fine
* Tested with:
  * `ionic serve` on Chrome
  * OnePlus6T on Android 10
  * iPhone on IOS 12.4.6

```
Ionic:

   Ionic CLI                     : 6.11.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 5.3.2
   @angular-devkit/build-angular : 0.1000.8
   @angular-devkit/schematics    : 10.0.8
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.3

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 9.0.0, ios 6.1.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 14 other plugins)

Utility:

   cordova-res (update available: 0.15.1) : 0.9.0
   native-run (update available: 1.0.0)   : 0.3.0

System:

   Android SDK Tools : 26.1.1 (/Users/lorent/Library/Android/sdk)
   ios-deploy        : 1.10.0
   ios-sim           : 8.0.2
   NodeJS            : v14.2.0 (/usr/local/Cellar/node/14.2.0/bin/node)
   npm               : 6.14.5
   OS                : macOS Catalina
   Xcode             : Xcode 11.6 Build version 11E708
```

I have also tested `ionic serve` after re-adding `(window as any).process = {};` to `polyfill.ts`, and everything works fine.

**Comment by kygoh** [comment] 2020-09-01 23:32
I use [amazon-cognito-identity-js](https://www.npmjs.com/package/amazon-cognito-identity-js) and [aws-sdk](https://www.npmjs.com/package/aws-sdk). As described in [Part 2: Adding Authentication to your Angular Material & AWS Amplify powered PWA](https://itnext.io/part-2-adding-authentication-to-your-angular-material-aws-amplify-powered-pwa-2a9d0fbd305a):

> We also need to add a polyfill to the src/polyfills.ts file since Angular has (in 6+) removed the reference to global within the framework, (*updated for Angular 8, which has also has removed the process property, another server-side JavaScript attribute) which is referenced by AWS SDK components since the AWS SDK for JavaScript is also supported in a node.js environment, while Angular is not.
>
> Edit `src/polyfills.ts` and add the following line to the top of the file:
>
> ```ts
> (window as any).global = window;
> (window as any).process = {
>    env: { DEBUG: undefined },
> };
> ```

As @jbgtmartin explaned in https://github.com/ionic-team/ionic-storage/issues/161#issuecomment-683773237, "_then Ionic Storage will think that I'm in a node environment, and provide the [n]oop driver instead of IndexedDB or SQLite etc_."

`2.3.1-beta.1` appears to solve the problem.

**Comment by saikirangit** [comment] 2020-09-02 02:14
It worked for me too @mhartington

**Comment by jbgtmartin** [comment] 2020-09-02 07:45
`2.3.1-beta.1` works fine for me in Chrome with PouchDB, thanks!

**Comment by Boosten** [comment] 2020-09-25 08:20
I was using @ionic/storage in my Cypress integration tests when I stumbled into this issue. I can confirm it is working again in v2.3.1. 👍

**Comment by SimonBrazell** [comment] 2020-11-25 01:21
I've noticed that if I serve the app using Cordova browser platform via `ionic serve --cordova --platform browser` then storage doesn't work for me, however if I use just plain `ionic serve` then it does using v2.3.1.

**Comment by mhartington** [comment] 2020-11-25 01:38
@SimonBrazell cordova's platform browser is not a fully functional platform and we do not support it.  Since most people seem to be working fine here, Im going to close this issue.

**Closed by mhartington** 2020-11-25 01:38 UTC
