### ISSUE TITLE
Chrome switching between asyncStorage and webSQLStorage on page reload

### ISSUE THREAD

**Issue by MatthewAlner** [ionic-team/ionic-storage#188] opened 2020-06-30 09:01 UTC
version: "@ionic/storage": "^2.2.0"
chrome version: 83.0.4103.116 (Official Build) (64-bit)

On first page load it uses asyncStorage then on a hard refresh or if I make a code change and it reloads, it swaps to using webSQLStorage. This doesn't happen in Safari or Firefox as far as I can tell.

I have worked around the issue by specifying my drivers an omitting `websql`

```
    IonicStorageModule.forRoot({
      driverOrder: ['indexeddb', 'sqlite'],
    }),
```

before I didn't pass anything, `IonicStorageModule.forRoot()`

Here is a [video](https://youtu.be/CZN_cTlPd6U) of the issue

https://youtu.be/CZN_cTlPd6U

Cheers,

Matt

**Comment by lincolnthree** [comment] 2020-10-16 22:25
I believe this is the cause. LocalForage does not seem to detect Chrome's indexedDb reliably:

https://github.com/localForage/localForage/pull/999

Worse yet, `@ionic/storage` forces an internal version of localForage that needs to be overridden to patch this.

**Comment by mlynch** [comment] 2021-03-09 22:43
v3 which will be out in a few weeks uses the latest of localForage so going to close this

**Closed by mlynch** 2021-03-09 22:43 UTC

**Comment by lincolnthree** [comment] 2021-03-10 05:53
@mlynch I do not believe the fix was merged into localForage. This issue should probably not be closed.

To be honest, the localForage project seems mostly dead/unmaintained now. You might consider forking it or switching to something else.

**Comment by mlynch** [comment] 2021-03-10 14:57
Strange, I'm looking at your PR and it's essentially doing the same thing as the code that is already there. the `idb` isn't a chrome global, it's coming from the import in `utils/idb.js` which is pulling `window.indexedDB`. I would be shocked if `window.indexedDB` isn't available immediately as the script runs 🤔

**Comment by sebaferreras** [comment] 2023-06-02 21:11
@lincolnthree I think I'm experiencing the same issue... were you able to find a workaround or at least more information about why it happens? Thanks :)

**Comment by lincolnthree** [comment] 2023-06-03 04:01
My workaround was to fork localForage, use the PR I submitted, and force everything to use my verison -- since the project seems not to be maintained any longer.
